fib: fibonacci.c
	gcc fibonacci.c -o fibonacci.out
	./fibonacci.out 5

sums: sums.c
	gcc sums.c -o sums.out
	./sums.out

prog3: prog3.c
	gcc prog3.c -o prog3.out
	./prog3.out ls
	./prog3.out ls -a
	./prog3.out make fib
	./prog3.out find

clean:
	rm *.out